# Generated by Django 6.1 on 2026-08-31 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('start_date', models.DateField(help_text='First day the event is active.')),
                ('duration_days', models.PositiveIntegerField(default=1, help_text='Number of days the event stays live (auto end date).')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('live', 'Live'), ('closed', 'Closed')], default='draft', max_length=10)),
                ('public_slug', models.SlugField(blank=True, max_length=80, null=True, unique=True)),
                ('venue', models.CharField(blank=True, default='', max_length=200)),
                ('hall_name', models.CharField(blank=True, default='', max_length=200)),
                ('table_name', models.CharField(blank=True, default='', max_length=200)),
                ('reminder_hours_csv', models.CharField(blank=True, default='', help_text='Comma-separated hours before the meeting to email a reminder, e.g. 24,1', max_length=50)),
                ('inapp_lead_minutes', models.PositiveIntegerField(default=30, help_text='Minutes before a meeting to raise the in-app host notification.')),
                ('same_day_summary', models.BooleanField(default=True, help_text='Also send hosts a same-day summary of their meetings.')),
                ('require_phone', models.BooleanField(default=False)),
                ('require_company', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(blank=True, default='', help_text='Optional title shown to visitors.', max_length=120)),
                ('photo_url', models.URLField(blank=True, default='', help_text='Optional photo shown on the roster (FR-4.2).')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive hosts are hidden from visitors; their bookings get flagged for admin attention (FR-2.3).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='events.event')),
                ('linked_user', models.ForeignKey(blank=True, help_text='Optional admin login; when signed in, this host sees their own schedule and reminders.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='host_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('mode', models.CharField(choices=[('online', 'Online (video call)'), ('offline', 'Offline (at venue)')], default='online', max_length=10)),
                ('video_provider', models.CharField(blank=True, choices=[('google_meet', 'Google Meet'), ('zoom', 'Zoom')], default='', max_length=20)),
                ('meeting_link', models.URLField(blank=True, default='')),
                ('venue', models.CharField(blank=True, default='', max_length=200)),
                ('hall_name', models.CharField(blank=True, default='', max_length=200)),
                ('table_name', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('cancelled', 'Cancelled / Reopened'), ('closed', 'Closed')], default='available', max_length=12)),
                ('capacity', models.PositiveIntegerField(default=1, help_text='How many visitors may hold this slot (BR-03; default 1).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='events.event')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='events.teammember')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('event', 'email'), name='unique_host_per_event'),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('host', 'date', 'start_time'), name='unique_host_date_time'),
        ),
    ]
