# Generated by Django 6.1 on 2026-09-01 04:42

from django.db import migrations, models


def backfill_event_type(apps, schema_editor):
    """Derive each existing event's single type from the slots it already has.

    Pre-existing data allowed mixed modes per slot; the majority mode wins and
    every slot is then normalised to it, because an event is strictly one type
    from here on. Events with no slots keep the 'online' default.
    """
    Event = apps.get_model("events", "Event")
    for event in Event.objects.all():
        modes = list(event.slots.values_list("mode", flat=True))
        if modes and modes.count("offline") > modes.count("online"):
            event.event_type = "offline"
        elif modes:
            event.event_type = "online"
        if event.event_type == "offline":
            event.default_video_provider = ""
            event.default_meeting_link = ""
            event.slots.update(mode="offline", video_provider="", meeting_link="")
        else:
            # Carry the first slot's provider/link up as the event default so
            # existing online slots keep working unchanged.
            first = event.slots.exclude(meeting_link="").first()
            if first is not None:
                event.default_video_provider = first.video_provider
                event.default_meeting_link = first.meeting_link
            event.venue = event.hall_name = event.table_name = ""
            event.slots.update(mode="online", venue="", hall_name="", table_name="")
        event.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='default_meeting_link',
            field=models.URLField(blank=True, default='', help_text='Meeting link created manually in Meet/Zoom; slots inherit it unless they set their own.'),
        ),
        migrations.AddField(
            model_name='event',
            name='default_video_provider',
            field=models.CharField(blank=True, choices=[('google_meet', 'Google Meet'), ('zoom', 'Zoom')], default='', help_text='Provider label shown to visitors (Google Meet or Zoom).', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('online', 'Online — video call'), ('offline', 'Offline — in person at a venue')], default='online', help_text='Set once at creation; locked as soon as the event has slots.', max_length=10),
        ),
        migrations.AlterField(
            model_name='slot',
            name='mode',
            field=models.CharField(choices=[('online', 'Online (video call)'), ('offline', 'Offline (at venue)')], default='online', help_text="Mirrors the parent event's type — never set directly.", max_length=10),
        ),
        migrations.RunPython(backfill_event_type, noop),
    ]
