# Generated by Django 6.1 on 2026-09-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_default_meeting_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('cancelled', 'Cancelled / Reopened'), ('closed', 'Closed'), ('break', 'Break')], default='available', max_length=12),
        ),
    ]
