# Generated by Django 6.1 on 2026-09-03 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_active_weekdays'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(help_text='One directory entry per email address.', max_length=254, unique=True)),
                ('role', models.CharField(blank=True, default='', help_text='Optional title shown to visitors.', max_length=120)),
                ('photo_url', models.URLField(blank=True, default='', help_text='Optional photo shown on the host roster (FR-4.2).')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive people are hidden from the “add hosts” picker but keep their hosting history.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_user', models.ForeignKey(blank=True, help_text='Optional admin login; when signed in, this person sees their own schedule and reminders.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='teammember',
            name='person',
            field=models.ForeignKey(blank=True, help_text='Directory entry this host was picked from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='events.person'),
        ),
    ]
