# Generated by Django 6.1 on 2026-09-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_person_teammember_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optional uploaded photo — shown instead of the photo link when present.', null=True, upload_to='people/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optional uploaded photo — shown instead of the photo link when present.', null=True, upload_to='people/%Y/%m/'),
        ),
    ]
