# Generated by Django 6.1.1 on 2026-09-03 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_person_teammember_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='default_video_provider',
            field=models.CharField(blank=True, choices=[('google_meet', 'Google Meet'), ('zoom', 'Zoom'), ('jitsi', 'Auto (private room)')], default='', help_text='Provider label shown to visitors (Google Meet or Zoom).', max_length=20),
        ),
        migrations.AlterField(
            model_name='slot',
            name='video_provider',
            field=models.CharField(blank=True, choices=[('google_meet', 'Google Meet'), ('zoom', 'Zoom'), ('jitsi', 'Auto (private room)')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='EventDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('skipped', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_settings', to='events.event')),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('event', 'date'), name='unique_event_day')],
            },
        ),
    ]
