# Generated by Django 6.1 on 2026-09-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_default_video_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='default_meeting_link',
            field=models.URLField(blank=True, default='', help_text='Optional room shared by every slot without its own link; blank means each slot gets its own auto-generated private room.'),
        ),
    ]
