# Generated by Django 6.1 on 2026-09-01 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, default='', help_text='Shown in emails and in the footer. Blank uses COMPANY_NAME.', max_length=100)),
                ('public_base_url', models.URLField(blank=True, default='', help_text='The address visitors use, e.g. https://book.traveldoor.ge. Every link in every email is built from this.')),
                ('email_host', models.CharField(blank=True, default='', help_text='SMTP server, e.g. smtp.gmail.com. Blank keeps using the environment configuration.', max_length=200)),
                ('email_port', models.PositiveIntegerField(default=587, help_text='587 for STARTTLS, 465 for SSL.')),
                ('email_host_user', models.CharField(blank=True, default='', help_text='Usually the full mailbox address.', max_length=200)),
                ('email_host_password_encrypted', models.TextField(blank=True, default='')),
                ('email_use_tls', models.BooleanField(default=True, help_text='STARTTLS — use with port 587.')),
                ('email_use_ssl', models.BooleanField(default=False, help_text='Implicit SSL — use with port 465.')),
                ('from_email', models.EmailField(blank=True, default='', help_text='The address every email is sent from, e.g. bookings@traveldoor.ge.', max_length=254)),
                ('from_name', models.CharField(blank=True, default='', help_text='Display name shown beside the from address.', max_length=100)),
                ('default_reminder_hours', models.CharField(blank=True, default='', help_text='Hours before a meeting to email a reminder, comma separated (e.g. 24,1). Used by events that do not set their own.', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
