# Generated by Django 6.1 on 2026-08-31 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('publish', 'Publish'), ('close', 'Close'), ('cancel', 'Cancel'), ('reschedule', 'Reschedule'), ('reactivate', 'Re-activate')], max_length=20)),
                ('entity_type', models.CharField(choices=[('Event', 'Event'), ('TeamMember', 'Team Member'), ('Slot', 'Slot'), ('Booking', 'Booking'), ('AdminAccount', 'Admin Account')], max_length=40)),
                ('entity_id', models.PositiveIntegerField()),
                ('entity_repr', models.CharField(blank=True, default='', help_text='Human label at time of action.', max_length=200)),
                ('details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Admin who performed the action (blank for system jobs).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit log entry',
                'verbose_name_plural': 'Audit log entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__289f08_idx'), models.Index(fields=['actor', 'created_at'], name='audit_audit_actor_i_d8a8b1_idx')],
            },
        ),
    ]
