# Generated by Django 6.1 on 2026-09-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogentry',
            name='entity_type',
            field=models.CharField(choices=[('Event', 'Event'), ('Person', 'Person'), ('TeamMember', 'Team Member'), ('Slot', 'Slot'), ('Booking', 'Booking'), ('AdminAccount', 'Admin Account')], max_length=40),
        ),
    ]
