# Generated by Django 6.1 on 2026-08-31 10:12

import bookings.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=200)),
                ('visitor_email', models.EmailField(max_length=254)),
                ('visitor_phone', models.CharField(blank=True, default='', max_length=40)),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional message from the visitor.')),
                ('manage_token', models.CharField(default=bookings.models.generate_manage_token, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=12)),
                ('needs_attention', models.BooleanField(default=False, help_text='Flagged for admin attention (e.g. host was removed from the event) — FR-2.3.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.event')),
                ('rescheduled_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='bookings.booking')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='events.slot')),
            ],
            options={
                'ordering': ['slot__date', 'slot__start_time'],
            },
        ),
    ]
