# Generated by Django 6.1 on 2026-08-31 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('upcoming', 'Upcoming meeting'), ('summary', 'Same-day summary'), ('flag', 'Attention flag')], default='upcoming', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('meeting_datetime', models.DateTimeField()),
                ('join_url', models.URLField(blank=True, default='', help_text='One-click join link for online meetings (FR-6.2).')),
                ('venue_details', models.CharField(blank=True, default='', max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='host_notifications', to='bookings.booking')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_notifications', to='events.event')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='events.teammember')),
            ],
            options={
                'ordering': ['-meeting_datetime'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('confirmation', 'Confirmation'), ('reminder', 'Reminder'), ('cancellation', 'Cancellation'), ('reschedule', 'Reschedule'), ('admin_account', 'Admin account'), ('attention', 'Attention')], max_length=20)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('in-app', 'In-app')], default='email', max_length=10)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, default='', max_length=250)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=10)),
                ('error', models.TextField(blank=True, default='')),
                ('meta', models.CharField(blank=True, default='', help_text="Dedup key, e.g. 'reminder-24'.", max_length=60)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Email / notification log',
                'ordering': ['-created_at'],
            },
        ),
    ]
