# Generated by Django 6.1.1 on 2026-09-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_schedulerheartbeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='type',
            field=models.CharField(choices=[('confirmation', 'Confirmation'), ('reminder', 'Reminder'), ('cancellation', 'Cancellation'), ('reschedule', 'Reschedule'), ('admin_account', 'Admin account'), ('attention', 'Attention'), ('password_reset', 'Password reset')], max_length=20),
        ),
    ]
